version: 1
lang: zh
generators:
  - key: block
    cached: true
    rules:
      - en: Block of {0}
        zh: "{0}块"
        subs:
          - material
  - key: material
    cached: true
    dict:
      - Amber: 琥珀