version: 1
lang: zh
generators:
  - group: block
    completed: true
    cached: true
    rules:
      - s: Block of {0}
        t: "{0}块"
        subs:
          - material
  - group: material
    completed: true
    cached: true
    dict:
      - Amber: 琥珀